# -*- coding: utf-8 -*-
"""Tugas 1 pratikum analisis kompleksitas algoritma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0NL-1yhu5N_dSU4FQ3x9qbyZwQE8Qne
"""

#Tugas pratikum 1

y = int(input("Masukan angka faktorial: "))

def faktorial(y):
  if y ==1:
    return 1
  else:
    return y * faktorial(y-1)

print(faktorial(y))